#include "mainwindow.h"
#include "ui_mainwindow.h"

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);  // setup ui from .ui file (corresponding "ui_mainwindow.h" file is generated by the user interface compiler (uic)
    myTimer = new SimpleTimer(*ui);
}

MainWindow::~MainWindow()
{
    delete myTimer;
    delete ui;
}

void MainWindow::on_pushButton_clicked() const
{
    myTimer->startStopTimer();
}

void MainWindow::on_lineEdit_textEdited(const QString &arg1) const
{
    ui->pushButton->setEnabled( (arg1.length() > 0) ); // disable pushbutton if user input is empty
}
