name: build-qt-program

on: push

jobs:
  build-qt-program:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/build/'
      - uses: actions/checkout@v3
      - run: mkdir test
