name: build-qt-program

on: push

jobs:
  build-qt-program:
    runs-on: windows-latest
    steps:
      - run: ls
      - uses: actions/checkout@v3
      - run: mkdir build
      - run: cd build
      - run: C:\Qt\5.15.2\mingw81_64\bin\qmake.exe ../src/LittleTimer.pro
      - run: make
