name: build-qt-program

on: push

jobs:
  build-qt-program:
    runs-on: windows-latest
    steps:
      - name: Install Qt
        run: choco install qt5-default
      - uses: actions/checkout@v3
      - run: ${{env.Qt5_Dir}}\qmake.exe src\LittleTimer.pro
      - run: make
